# Thanks to Verwoerd
# https://github.com/Programming-Contest-Foundation/logo/blob/main/domjudge/docker-compose.yml
services:
  mariadb:
    image: mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=domjudge
      - MYSQL_DATABASE=domjudge
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
  domjudge:
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:12345"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 1m
    image: ghcr.io/wisvch/domjudge-packaging/domserver
    hostname: domserver
    depends_on:
      - mariadb
    environment:
      - DJ_DB_INSTALL_BARE=1
    ports:
      - 12345:80
    volumes:
      - ${PWD}/out/contest-package:/tmp/icpc-logos
  #  entrypoint: ["/bin/bash","-c","sleep 1m && /scripts/start.sh"]
  #  hostname: domserver
  #  #privileged: true
#  cds:
#    image: ghcr.io/icpctools/cds:2.6.1161
#    depends_on:
#      - domjudge
#    ports:
#      - 12346:8080
#      - 12347:8443
#    environment:
#      - ADMIN_PASSWORD=blaat123
#      - PRESENTATION_PASSWORD=blaat123
#      - CCS_URL=http://domserver/api/contests/demo
#      - CCS_USER=feed
#      - CCS_PASSWORD=blaat123123
#    volumes:
#      - ../../../out/contest-package:/contest